//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AJA_tbl_FieldValues
    {
        public int UserID { get; set; }
        public int OptionID { get; set; }
        public string Value { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual AJA_tbl_FieldOptions AJA_tbl_FieldOptions { get; set; }
        public virtual AJA_tbl_Users AJA_tbl_Users { get; set; }
    }
}
