//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AJA_tbl_UserFields
    {
        public AJA_tbl_UserFields()
        {
            this.AJA_tbl_FieldOptions = new HashSet<AJA_tbl_FieldOptions>();
        }
    
        public int UserFieldID { get; set; }
        public int RoleID { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> ShowOrder { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsMandatory { get; set; }
        public Nullable<bool> DisplayYN { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual ICollection<AJA_tbl_FieldOptions> AJA_tbl_FieldOptions { get; set; }
        public virtual AJA_tbl_Roles AJA_tbl_Roles { get; set; }
        public virtual AJA_tbl_FieldTypes AJA_tbl_FieldTypes { get; set; }
    }
}
