//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AJA_tbl_Roles
    {
        public AJA_tbl_Roles()
        {
            this.AJA_tbl_UserFields = new HashSet<AJA_tbl_UserFields>();
            this.AJA_tbl_Users = new HashSet<AJA_tbl_Users>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<AJA_tbl_UserFields> AJA_tbl_UserFields { get; set; }
        public virtual ICollection<AJA_tbl_Users> AJA_tbl_Users { get; set; }
    }
}
