//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AJA_tbl_FieldOptions
    {
        public AJA_tbl_FieldOptions()
        {
            this.AJA_tbl_FieldValues = new HashSet<AJA_tbl_FieldValues>();
        }
    
        public int OptionID { get; set; }
        public int UserFieldID { get; set; }
        public string OptionText { get; set; }
        public string OptionValue { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual AJA_tbl_UserFields AJA_tbl_UserFields { get; set; }
        public virtual ICollection<AJA_tbl_FieldValues> AJA_tbl_FieldValues { get; set; }
    }
}
