//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AJA_tbl_Users
    {
        public AJA_tbl_Users()
        {
            this.AJA_tbl_FieldValues = new HashSet<AJA_tbl_FieldValues>();
            this.AJA_tbl_Roles = new HashSet<AJA_tbl_Roles>();
        }
    
        public int UserID { get; set; }
        public string EmailID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Activated { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Pincode { get; set; }
        public Nullable<int> specialtyID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> graduationYear { get; set; }
        public string profession { get; set; }
        public Nullable<int> typePracticeID { get; set; }
        public string UserTitle { get; set; }
        public bool IseditorEmaiSend { get; set; }
        public Nullable<bool> IsSavedAqemaisend { get; set; }
        public string deleted_ind { get; set; }
        public Nullable<bool> surveyValidated { get; set; }
        public string userType { get; set; }
        public string yrsPractice { get; set; }
    
        public virtual ICollection<AJA_tbl_FieldValues> AJA_tbl_FieldValues { get; set; }
        public virtual ICollection<AJA_tbl_Roles> AJA_tbl_Roles { get; set; }
    }
}
