//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticlesAuthor
    {
        public long GeneID { get; set; }
        public int ArticleID { get; set; }
        public string AuthorName { get; set; }
        public int SortOrder { get; set; }
    
        public virtual GenesArticle GenesArticle { get; set; }
    }
}
