//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleSelection
    {
        public int ThreadID { get; set; }
        public int PMID { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual EditorialThread EditorialThread { get; set; }
    }
}
