//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentAuthor
    {
        public CommentAuthor()
        {
            this.EditorialComments = new HashSet<EditorialComment>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string affiliations { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<EditorialComment> EditorialComments { get; set; }
    }
}
