//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc
    {
        public doc()
        {
            this.doc_in_subtopic = new HashSet<doc_in_subtopic>();
        }
    
        public int id { get; set; }
        public string source { get; set; }
        public string nm { get; set; }
        public System.DateTime last_updated_dt { get; set; }
        public string auto_upd { get; set; }
        public int clicks_count { get; set; }
    
        public virtual ICollection<doc_in_subtopic> doc_in_subtopic { get; set; }
    }
}
