//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_in_subtopic
    {
        public int id { get; set; }
        public int subtopic_id { get; set; }
        public int doc_id { get; set; }
    
        public virtual doc doc { get; set; }
    }
}
