//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EditorsEntities : DbContext
    {
        public EditorsEntities()
            : base("name=EditorsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AtLargeEditor> AtLargeEditors { get; set; }
        public DbSet<CommentAuthor> CommentAuthors { get; set; }
        public DbSet<EditorTopic> EditorTopics { get; set; }
        public DbSet<Specialty> Specialties { get; set; }
        public DbSet<Topic> Topics { get; set; }
        public DbSet<ArticleSelection> ArticleSelections { get; set; }
        public DbSet<Edition> Editions { get; set; }
        public DbSet<EditorialThread> EditorialThreads { get; set; }
        public DbSet<SubTopicEditorRef> SubTopicEditorRefs { get; set; }
        public DbSet<SubTopicReference> SubTopicReferences { get; set; }
        public DbSet<doc_in_subtopic> doc_in_subtopic { get; set; }
        public DbSet<doc> docs { get; set; }
        public DbSet<SubTopic> SubTopics { get; set; }
        public DbSet<Gene> Genes { get; set; }
        public DbSet<EditorialComment> EditorialComments { get; set; }
        public DbSet<vwRecentEdition> vwRecentEditions { get; set; }
        public DbSet<CustomMailHeader> CustomMailHeaders { get; set; }
        public DbSet<UserSpecialty> UserSpecialties { get; set; }
        public DbSet<AJA_tbl_FieldOptions> AJA_tbl_FieldOptions { get; set; }
        public DbSet<AJA_tbl_FieldTypes> AJA_tbl_FieldTypes { get; set; }
        public DbSet<AJA_tbl_FieldValues> AJA_tbl_FieldValues { get; set; }
        public DbSet<AJA_tbl_Roles> AJA_tbl_Roles { get; set; }
        public DbSet<AJA_tbl_UserFields> AJA_tbl_UserFields { get; set; }
        public DbSet<AJA_tbl_Users> AJA_tbl_Users { get; set; }
        public DbSet<UserCitation> UserCitations { get; set; }
        public DbSet<UserHasSponsorFolder> UserHasSponsorFolders { get; set; }
        public DbSet<HiddenTopic> HiddenTopics { get; set; }
        public DbSet<HiddenSubTopic> HiddenSubTopics { get; set; }
        public DbSet<SponsorTopic> SponsorTopics { get; set; }
        public DbSet<UserHasSponsorTopic> UserHasSponsorTopics { get; set; }
        public DbSet<Test> Tests { get; set; }
        public DbSet<GeneAlias> GeneAliases { get; set; }
        public DbSet<CitationsGene> CitationsGenes { get; set; }
        public DbSet<UserComment> UserComments { get; set; }
        public DbSet<GenesLink> GenesLinks { get; set; }
        public DbSet<GeneCommentCombo> GeneCommentCombos { get; set; }
        public DbSet<GeneComment> GeneComments { get; set; }
        public DbSet<TestCommentCombo> TestCommentCombos { get; set; }
        public DbSet<TestComment> TestComments { get; set; }
        public DbSet<CitationsTest> CitationsTests { get; set; }
        public DbSet<SponsorFolder> SponsorFolders { get; set; }
        public DbSet<TestsLink> TestsLinks { get; set; }
        public DbSet<ArticlesAuthor> ArticlesAuthors { get; set; }
        public DbSet<GenesArticle> GenesArticles { get; set; }
        public DbSet<NonMedlineCitation> NonMedlineCitations { get; set; }
    
        public virtual int adm_DeleteThread(Nullable<int> threadID)
        {
            var threadIDParameter = threadID.HasValue ?
                new ObjectParameter("ThreadID", threadID) :
                new ObjectParameter("ThreadID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("adm_DeleteThread", threadIDParameter);
        }
    
        public virtual ObjectResult<adm_GetThreads_Result> adm_GetThreads(Nullable<int> editionID)
        {
            var editionIDParameter = editionID.HasValue ?
                new ObjectParameter("EditionID", editionID) :
                new ObjectParameter("EditionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<adm_GetThreads_Result>("adm_GetThreads", editionIDParameter);
        }
    
        public virtual int adm_DeleteEditorialComment(Nullable<int> commentID)
        {
            var commentIDParameter = commentID.HasValue ?
                new ObjectParameter("CommentID", commentID) :
                new ObjectParameter("CommentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("adm_DeleteEditorialComment", commentIDParameter);
        }
    
        public virtual ObjectResult<adm_GetThreadComments_Result> adm_GetThreadComments(Nullable<int> threadID)
        {
            var threadIDParameter = threadID.HasValue ?
                new ObjectParameter("ThreadID", threadID) :
                new ObjectParameter("ThreadID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<adm_GetThreadComments_Result>("adm_GetThreadComments", threadIDParameter);
        }
    
        public virtual int adm_InsertEditorialComment(Nullable<int> threadID, Nullable<int> authorID, Nullable<int> sortOrder, string comment)
        {
            var threadIDParameter = threadID.HasValue ?
                new ObjectParameter("ThreadID", threadID) :
                new ObjectParameter("ThreadID", typeof(int));
    
            var authorIDParameter = authorID.HasValue ?
                new ObjectParameter("AuthorID", authorID) :
                new ObjectParameter("AuthorID", typeof(int));
    
            var sortOrderParameter = sortOrder.HasValue ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(int));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("adm_InsertEditorialComment", threadIDParameter, authorIDParameter, sortOrderParameter, commentParameter);
        }
    
        public virtual int lib_AddEditorCommentToGene(Nullable<int> geneID, Nullable<int> commentID)
        {
            var geneIDParameter = geneID.HasValue ?
                new ObjectParameter("GeneID", geneID) :
                new ObjectParameter("GeneID", typeof(int));
    
            var commentIDParameter = commentID.HasValue ?
                new ObjectParameter("CommentID", commentID) :
                new ObjectParameter("CommentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lib_AddEditorCommentToGene", geneIDParameter, commentIDParameter);
        }
    
        public virtual ObjectResult<adm_GetECMailingByEdition_Result> adm_GetECMailingByEdition(Nullable<int> editionID)
        {
            var editionIDParameter = editionID.HasValue ?
                new ObjectParameter("EditionID", editionID) :
                new ObjectParameter("EditionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<adm_GetECMailingByEdition_Result>("adm_GetECMailingByEdition", editionIDParameter);
        }
    
        public virtual int lib_DeleteSearchesFromSubTopic(Nullable<int> subTopicID, Nullable<int> userID)
        {
            var subTopicIDParameter = subTopicID.HasValue ?
                new ObjectParameter("SubTopicID", subTopicID) :
                new ObjectParameter("SubTopicID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lib_DeleteSearchesFromSubTopic", subTopicIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<lib_GetECEditorSort_Result> lib_GetECEditorSort(Nullable<int> editionID)
        {
            var editionIDParameter = editionID.HasValue ?
                new ObjectParameter("EditionID", editionID) :
                new ObjectParameter("EditionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetECEditorSort_Result>("lib_GetECEditorSort", editionIDParameter);
        }
    
        public virtual ObjectResult<lib_GetRelatedEditions_Result> lib_GetRelatedEditions(Nullable<int> pMID, Nullable<int> editionID)
        {
            var pMIDParameter = pMID.HasValue ?
                new ObjectParameter("PMID", pMID) :
                new ObjectParameter("PMID", typeof(int));
    
            var editionIDParameter = editionID.HasValue ?
                new ObjectParameter("EditionID", editionID) :
                new ObjectParameter("EditionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetRelatedEditions_Result>("lib_GetRelatedEditions", pMIDParameter, editionIDParameter);
        }
    
        public virtual ObjectResult<lib_GetECThreadComments_Result> lib_GetECThreadComments(Nullable<int> editionID, Nullable<int> threadID)
        {
            var editionIDParameter = editionID.HasValue ?
                new ObjectParameter("EditionID", editionID) :
                new ObjectParameter("EditionID", typeof(int));
    
            var threadIDParameter = threadID.HasValue ?
                new ObjectParameter("ThreadID", threadID) :
                new ObjectParameter("ThreadID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetECThreadComments_Result>("lib_GetECThreadComments", editionIDParameter, threadIDParameter);
        }
    
        public virtual int lib_DeleteUserAutoQueries(Nullable<int> specialtyID, Nullable<int> userID)
        {
            var specialtyIDParameter = specialtyID.HasValue ?
                new ObjectParameter("SpecialtyID", specialtyID) :
                new ObjectParameter("SpecialtyID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lib_DeleteUserAutoQueries", specialtyIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<lib_GetGenesForEditorsChoice_Result> lib_GetGenesForEditorsChoice(Nullable<int> commentID)
        {
            var commentIDParameter = commentID.HasValue ?
                new ObjectParameter("CommentID", commentID) :
                new ObjectParameter("CommentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetGenesForEditorsChoice_Result>("lib_GetGenesForEditorsChoice", commentIDParameter);
        }
    
        public virtual ObjectResult<lib_GetUnsubscribedSpecialties_Result> lib_GetUnsubscribedSpecialties(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetUnsubscribedSpecialties_Result>("lib_GetUnsubscribedSpecialties", userIDParameter);
        }
    
        public virtual int lib_RemoveSponsorTopic(Nullable<int> userID, Nullable<int> topicID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var topicIDParameter = topicID.HasValue ?
                new ObjectParameter("TopicID", topicID) :
                new ObjectParameter("TopicID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lib_RemoveSponsorTopic", userIDParameter, topicIDParameter);
        }
    
        public virtual ObjectResult<lib_GetSavedCitationList_Result> lib_GetSavedCitationList(Nullable<int> userID, Nullable<int> subTopicID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var subTopicIDParameter = subTopicID.HasValue ?
                new ObjectParameter("SubTopicID", subTopicID) :
                new ObjectParameter("SubTopicID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetSavedCitationList_Result>("lib_GetSavedCitationList", userIDParameter, subTopicIDParameter);
        }
    
        public virtual int adm_AddEditorCommentToGene(Nullable<int> geneID, Nullable<int> commentID)
        {
            var geneIDParameter = geneID.HasValue ?
                new ObjectParameter("GeneID", geneID) :
                new ObjectParameter("GeneID", typeof(int));
    
            var commentIDParameter = commentID.HasValue ?
                new ObjectParameter("CommentID", commentID) :
                new ObjectParameter("CommentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("adm_AddEditorCommentToGene", geneIDParameter, commentIDParameter);
        }
    
        public virtual int adm_DeleteEditorCommentFromGene(Nullable<int> geneID, Nullable<int> commentID)
        {
            var geneIDParameter = geneID.HasValue ?
                new ObjectParameter("GeneID", geneID) :
                new ObjectParameter("GeneID", typeof(int));
    
            var commentIDParameter = commentID.HasValue ?
                new ObjectParameter("CommentID", commentID) :
                new ObjectParameter("CommentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("adm_DeleteEditorCommentFromGene", geneIDParameter, commentIDParameter);
        }
    
        public virtual ObjectResult<lib_GetGeneEditorCommentsByGeneID_Result> lib_GetGeneEditorCommentsByGeneID(Nullable<int> geneID)
        {
            var geneIDParameter = geneID.HasValue ?
                new ObjectParameter("GeneID", geneID) :
                new ObjectParameter("GeneID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetGeneEditorCommentsByGeneID_Result>("lib_GetGeneEditorCommentsByGeneID", geneIDParameter);
        }
    
        public virtual ObjectResult<lib_GetAbstractCommentsEC20_Result> lib_GetAbstractCommentsEC20(Nullable<int> pMID)
        {
            var pMIDParameter = pMID.HasValue ?
                new ObjectParameter("PMID", pMID) :
                new ObjectParameter("PMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetAbstractCommentsEC20_Result>("lib_GetAbstractCommentsEC20", pMIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> lib_GetEditorsChoiceCitations(Nullable<int> subTopicID)
        {
            var subTopicIDParameter = subTopicID.HasValue ?
                new ObjectParameter("SubTopicID", subTopicID) :
                new ObjectParameter("SubTopicID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("lib_GetEditorsChoiceCitations", subTopicIDParameter);
        }
    
        public virtual ObjectResult<lib_GetEditorsChoiceExtraInfo_Result> lib_GetEditorsChoiceExtraInfo(Nullable<int> userID, Nullable<int> subTopicID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var subTopicIDParameter = subTopicID.HasValue ?
                new ObjectParameter("SubTopicID", subTopicID) :
                new ObjectParameter("SubTopicID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetEditorsChoiceExtraInfo_Result>("lib_GetEditorsChoiceExtraInfo", userIDParameter, subTopicIDParameter);
        }
    
        public virtual ObjectResult<lib_GetUserSubTopics_Result> lib_GetUserSubTopics(Nullable<int> userID, Nullable<int> topicID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var topicIDParameter = topicID.HasValue ?
                new ObjectParameter("TopicID", topicID) :
                new ObjectParameter("TopicID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetUserSubTopics_Result>("lib_GetUserSubTopics", userIDParameter, topicIDParameter);
        }
    
        public virtual ObjectResult<lib_GetSemCitExtraInfo_Result> lib_GetSemCitExtraInfo(Nullable<int> userID, Nullable<int> subTopicID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var subTopicIDParameter = subTopicID.HasValue ?
                new ObjectParameter("SubTopicID", subTopicID) :
                new ObjectParameter("SubTopicID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetSemCitExtraInfo_Result>("lib_GetSemCitExtraInfo", userIDParameter, subTopicIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> lib_GetSeminalCitations(Nullable<int> subTopicID)
        {
            var subTopicIDParameter = subTopicID.HasValue ?
                new ObjectParameter("SubTopicID", subTopicID) :
                new ObjectParameter("SubTopicID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("lib_GetSeminalCitations", subTopicIDParameter);
        }
    
        public virtual ObjectResult<lib_GetSponCitExtraInfo_Result> lib_GetSponCitExtraInfo(Nullable<int> userID, Nullable<int> subTopicID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var subTopicIDParameter = subTopicID.HasValue ?
                new ObjectParameter("SubTopicID", subTopicID) :
                new ObjectParameter("SubTopicID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetSponCitExtraInfo_Result>("lib_GetSponCitExtraInfo", userIDParameter, subTopicIDParameter);
        }
    
        public virtual ObjectResult<doc_in_subtopic_find_Result> doc_in_subtopic_find(Nullable<int> id, Nullable<int> subtopic_id, Nullable<int> doc_id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var subtopic_idParameter = subtopic_id.HasValue ?
                new ObjectParameter("subtopic_id", subtopic_id) :
                new ObjectParameter("subtopic_id", typeof(int));
    
            var doc_idParameter = doc_id.HasValue ?
                new ObjectParameter("doc_id", doc_id) :
                new ObjectParameter("doc_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doc_in_subtopic_find_Result>("doc_in_subtopic_find", idParameter, subtopic_idParameter, doc_idParameter);
        }
    
        public virtual ObjectResult<lib_GetTestEditorCommentsByTestID_Result> lib_GetTestEditorCommentsByTestID(Nullable<int> testID)
        {
            var testIDParameter = testID.HasValue ?
                new ObjectParameter("TestID", testID) :
                new ObjectParameter("TestID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetTestEditorCommentsByTestID_Result>("lib_GetTestEditorCommentsByTestID", testIDParameter);
        }
    
        public virtual int adm_AddEditorCommentToTest(Nullable<int> testID, Nullable<int> commentID)
        {
            var testIDParameter = testID.HasValue ?
                new ObjectParameter("TestID", testID) :
                new ObjectParameter("TestID", typeof(int));
    
            var commentIDParameter = commentID.HasValue ?
                new ObjectParameter("CommentID", commentID) :
                new ObjectParameter("CommentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("adm_AddEditorCommentToTest", testIDParameter, commentIDParameter);
        }
    
        public virtual int adm_DeleteEditorCommentFromTest(Nullable<int> testID, Nullable<int> commentID)
        {
            var testIDParameter = testID.HasValue ?
                new ObjectParameter("TestID", testID) :
                new ObjectParameter("TestID", typeof(int));
    
            var commentIDParameter = commentID.HasValue ?
                new ObjectParameter("CommentID", commentID) :
                new ObjectParameter("CommentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("adm_DeleteEditorCommentFromTest", testIDParameter, commentIDParameter);
        }
    
        public virtual int lib_CreateSponsorFolderSFE(Nullable<int> userID, Nullable<int> userSpecialty, Nullable<int> sponsorFolderID, ObjectParameter topicFolderID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var userSpecialtyParameter = userSpecialty.HasValue ?
                new ObjectParameter("UserSpecialty", userSpecialty) :
                new ObjectParameter("UserSpecialty", typeof(int));
    
            var sponsorFolderIDParameter = sponsorFolderID.HasValue ?
                new ObjectParameter("SponsorFolderID", sponsorFolderID) :
                new ObjectParameter("SponsorFolderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lib_CreateSponsorFolderSFE", userIDParameter, userSpecialtyParameter, sponsorFolderIDParameter, topicFolderID);
        }
    
        public virtual ObjectResult<lib_GetGenesForCitation_Result> lib_GetGenesForCitation(Nullable<int> pMID)
        {
            var pMIDParameter = pMID.HasValue ?
                new ObjectParameter("PMID", pMID) :
                new ObjectParameter("PMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetGenesForCitation_Result>("lib_GetGenesForCitation", pMIDParameter);
        }
    
        public virtual ObjectResult<lib_GetGenesForThread_Result> lib_GetGenesForThread(Nullable<int> pMID)
        {
            var pMIDParameter = pMID.HasValue ?
                new ObjectParameter("PMID", pMID) :
                new ObjectParameter("PMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetGenesForThread_Result>("lib_GetGenesForThread", pMIDParameter);
        }
    
        public virtual ObjectResult<lib_GetTestsForCitation_Result> lib_GetTestsForCitation(Nullable<int> pMID)
        {
            var pMIDParameter = pMID.HasValue ?
                new ObjectParameter("PMID", pMID) :
                new ObjectParameter("PMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetTestsForCitation_Result>("lib_GetTestsForCitation", pMIDParameter);
        }
    
        public virtual ObjectResult<lib_GetTestsForThread_Result> lib_GetTestsForThread(Nullable<int> pMID)
        {
            var pMIDParameter = pMID.HasValue ?
                new ObjectParameter("PMID", pMID) :
                new ObjectParameter("PMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetTestsForThread_Result>("lib_GetTestsForThread", pMIDParameter);
        }
    
        public virtual ObjectResult<lib_GetGenesForEditorComments_Result> lib_GetGenesForEditorComments(Nullable<int> pMID)
        {
            var pMIDParameter = pMID.HasValue ?
                new ObjectParameter("PMID", pMID) :
                new ObjectParameter("PMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetGenesForEditorComments_Result>("lib_GetGenesForEditorComments", pMIDParameter);
        }
    
        public virtual ObjectResult<lib_GetTestsForEditorComments_Result> lib_GetTestsForEditorComments(Nullable<int> pMID)
        {
            var pMIDParameter = pMID.HasValue ?
                new ObjectParameter("PMID", pMID) :
                new ObjectParameter("PMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetTestsForEditorComments_Result>("lib_GetTestsForEditorComments", pMIDParameter);
        }
    
        public virtual int adm_AttachGeneToTest(Nullable<int> testID, Nullable<int> geneID)
        {
            var testIDParameter = testID.HasValue ?
                new ObjectParameter("TestID", testID) :
                new ObjectParameter("TestID", typeof(int));
    
            var geneIDParameter = geneID.HasValue ?
                new ObjectParameter("GeneID", geneID) :
                new ObjectParameter("GeneID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("adm_AttachGeneToTest", testIDParameter, geneIDParameter);
        }
    
        public virtual int adm_DeleteGene(Nullable<int> geneID)
        {
            var geneIDParameter = geneID.HasValue ?
                new ObjectParameter("GeneID", geneID) :
                new ObjectParameter("GeneID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("adm_DeleteGene", geneIDParameter);
        }
    
        public virtual int adm_DeleteTestByTestID(Nullable<int> testID)
        {
            var testIDParameter = testID.HasValue ?
                new ObjectParameter("TestID", testID) :
                new ObjectParameter("TestID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("adm_DeleteTestByTestID", testIDParameter);
        }
    
        public virtual int adm_UnlinkGeneFromTest(Nullable<int> testID, Nullable<int> geneID)
        {
            var testIDParameter = testID.HasValue ?
                new ObjectParameter("TestID", testID) :
                new ObjectParameter("TestID", typeof(int));
    
            var geneIDParameter = geneID.HasValue ?
                new ObjectParameter("GeneID", geneID) :
                new ObjectParameter("GeneID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("adm_UnlinkGeneFromTest", testIDParameter, geneIDParameter);
        }
    
        public virtual ObjectResult<lib_GetGenesForTestByTestID_Result> lib_GetGenesForTestByTestID(Nullable<int> testID)
        {
            var testIDParameter = testID.HasValue ?
                new ObjectParameter("TestID", testID) :
                new ObjectParameter("TestID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetGenesForTestByTestID_Result>("lib_GetGenesForTestByTestID", testIDParameter);
        }
    
        public virtual ObjectResult<lib_GetTestsForGeneByGeneID_Result> lib_GetTestsForGeneByGeneID(Nullable<int> geneID)
        {
            var geneIDParameter = geneID.HasValue ?
                new ObjectParameter("GeneID", geneID) :
                new ObjectParameter("GeneID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetTestsForGeneByGeneID_Result>("lib_GetTestsForGeneByGeneID", geneIDParameter);
        }
    
        public virtual ObjectResult<lib_GetEditorsChoiceCommentsForGeneByGeneID_Result> lib_GetEditorsChoiceCommentsForGeneByGeneID(Nullable<int> geneID)
        {
            var geneIDParameter = geneID.HasValue ?
                new ObjectParameter("GeneID", geneID) :
                new ObjectParameter("GeneID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetEditorsChoiceCommentsForGeneByGeneID_Result>("lib_GetEditorsChoiceCommentsForGeneByGeneID", geneIDParameter);
        }
    
        public virtual ObjectResult<lib_GetEditorsChoiceCommentsForTestByTestID_Result> lib_GetEditorsChoiceCommentsForTestByTestID(Nullable<int> testID)
        {
            var testIDParameter = testID.HasValue ?
                new ObjectParameter("TestID", testID) :
                new ObjectParameter("TestID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lib_GetEditorsChoiceCommentsForTestByTestID_Result>("lib_GetEditorsChoiceCommentsForTestByTestID", testIDParameter);
        }
    
        public virtual int lib_GetGeneLinksByGeneID(Nullable<int> geneID, Nullable<int> num)
        {
            var geneIDParameter = geneID.HasValue ?
                new ObjectParameter("GeneID", geneID) :
                new ObjectParameter("GeneID", typeof(int));
    
            var numParameter = num.HasValue ?
                new ObjectParameter("num", num) :
                new ObjectParameter("num", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lib_GetGeneLinksByGeneID", geneIDParameter, numParameter);
        }
    
        public virtual int lib_CopyUserCitation_MyQueries(Nullable<int> pmid, Nullable<int> subTopicID, Nullable<int> userid, Nullable<int> searchID, Nullable<System.DateTime> expireDate, Nullable<bool> keepDelete, ObjectParameter specialtyID)
        {
            var pmidParameter = pmid.HasValue ?
                new ObjectParameter("pmid", pmid) :
                new ObjectParameter("pmid", typeof(int));
    
            var subTopicIDParameter = subTopicID.HasValue ?
                new ObjectParameter("SubTopicID", subTopicID) :
                new ObjectParameter("SubTopicID", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var searchIDParameter = searchID.HasValue ?
                new ObjectParameter("SearchID", searchID) :
                new ObjectParameter("SearchID", typeof(int));
    
            var expireDateParameter = expireDate.HasValue ?
                new ObjectParameter("ExpireDate", expireDate) :
                new ObjectParameter("ExpireDate", typeof(System.DateTime));
    
            var keepDeleteParameter = keepDelete.HasValue ?
                new ObjectParameter("KeepDelete", keepDelete) :
                new ObjectParameter("KeepDelete", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("lib_CopyUserCitation_MyQueries", pmidParameter, subTopicIDParameter, useridParameter, searchIDParameter, expireDateParameter, keepDeleteParameter, specialtyID);
        }
    }
}
