//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditorialComment
    {
        public EditorialComment()
        {
            this.CommentAuthors = new HashSet<CommentAuthor>();
            this.Genes = new HashSet<Gene>();
        }
    
        public int CommentID { get; set; }
        public int ThreadID { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string Comment { get; set; }
    
        public virtual EditorialThread EditorialThread { get; set; }
        public virtual ICollection<CommentAuthor> CommentAuthors { get; set; }
        public virtual ICollection<Gene> Genes { get; set; }
    }
}
