//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditorialThread
    {
        public EditorialThread()
        {
            this.ArticleSelections = new HashSet<ArticleSelection>();
            this.SubTopicEditorRefs = new HashSet<SubTopicEditorRef>();
            this.SubTopicReferences = new HashSet<SubTopicReference>();
            this.EditorialComments = new HashSet<EditorialComment>();
        }
    
        public int ThreadID { get; set; }
        public System.DateTime OriginalPubDate { get; set; }
        public string ThreadName { get; set; }
    
        public virtual ICollection<ArticleSelection> ArticleSelections { get; set; }
        public virtual ICollection<SubTopicEditorRef> SubTopicEditorRefs { get; set; }
        public virtual ICollection<SubTopicReference> SubTopicReferences { get; set; }
        public virtual ICollection<EditorialComment> EditorialComments { get; set; }
    }
}
