//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edition
    {
        public Edition()
        {
            this.SubTopicEditorRefs = new HashSet<SubTopicEditorRef>();
            this.SubTopicReferences = new HashSet<SubTopicReference>();
        }
    
        public int EditionID { get; set; }
        public int SpecialtyID { get; set; }
        public System.DateTime PubDate { get; set; }
    
        public virtual ICollection<SubTopicEditorRef> SubTopicEditorRefs { get; set; }
        public virtual ICollection<SubTopicReference> SubTopicReferences { get; set; }
    }
}
