//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gene
    {
        public Gene()
        {
            this.EditorialComments = new HashSet<EditorialComment>();
            this.GeneAliases = new HashSet<GeneAlias>();
            this.CitationsGenes = new HashSet<CitationsGene>();
            this.GenesLinks = new HashSet<GenesLink>();
            this.GeneComments = new HashSet<GeneComment>();
            this.GenesArticles = new HashSet<GenesArticle>();
        }
    
        public long GeneID { get; set; }
        public string Name { get; set; }
        public string Symbol { get; set; }
        public string FullName { get; set; }
        public string Summary { get; set; }
    
        public virtual ICollection<EditorialComment> EditorialComments { get; set; }
        public virtual ICollection<GeneAlias> GeneAliases { get; set; }
        public virtual ICollection<CitationsGene> CitationsGenes { get; set; }
        public virtual ICollection<GenesLink> GenesLinks { get; set; }
        public virtual ICollection<GeneComment> GeneComments { get; set; }
        public virtual ICollection<GenesArticle> GenesArticles { get; set; }
    }
}
