//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneComment
    {
        public GeneComment()
        {
            this.GeneCommentCombos = new HashSet<GeneCommentCombo>();
        }
    
        public long GeneID { get; set; }
        public int id { get; set; }
        public int CommentID { get; set; }
        public string Comment { get; set; }
        public System.DateTime CommentDate { get; set; }
    
        public virtual ICollection<GeneCommentCombo> GeneCommentCombos { get; set; }
        public virtual Gene Gene { get; set; }
    }
}
