//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class iCitation
    {
        public int PMID { get; set; }
        public Nullable<int> MedlineID { get; set; }
        public byte StatusID { get; set; }
        public byte OwnerID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<System.DateTime> DateRevised { get; set; }
        public short NumberOfReferences { get; set; }
        public string AuthorList { get; set; }
        public string MedlineTA { get; set; }
        public string MedlinePgn { get; set; }
        public string DisplayDate { get; set; }
        public string DisplayNotes { get; set; }
        public short UpdateSource { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
