//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class iWide
    {
        public int PMID { get; set; }
        public string ArticleTitle { get; set; }
        public string AbstractText { get; set; }
        public string CopyrightInformation { get; set; }
        public string VernacularTitle { get; set; }
        public string Affiliation { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<bool> unicodeFixed { get; set; }
    }
}
