//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonMedlineCitation
    {
        public int PMID { get; set; }
        public string ArticleTitle { get; set; }
        public string AuthorList { get; set; }
        public string Abstract { get; set; }
        public Nullable<System.DateTime> CitationDate { get; set; }
        public string DisplayDate { get; set; }
        public string DisplayNotes { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string KeepDelete { get; set; }
        public string MedlinePgn { get; set; }
        public string MedlineTA { get; set; }
        public string Nickname { get; set; }
        public string SearchID { get; set; }
        public string Status { get; set; }
        public string StatusDisplay { get; set; }
        public Nullable<int> dps { get; set; }
    }
}
