//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchSummary
    {
        public int SearchID { get; set; }
        public int UserID { get; set; }
        public string SearchName { get; set; }
        public System.DateTime RunOriginal { get; set; }
        public int FoundOriginal { get; set; }
        public System.DateTime RunLast { get; set; }
        public int FoundLast { get; set; }
        public short PublicationTypeMask { get; set; }
        public byte LanguageMask { get; set; }
        public byte SpeciesMask { get; set; }
        public byte GenderMask { get; set; }
        public short SubjectAgeMask { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public byte AbstractMask { get; set; }
        public byte PaperAge { get; set; }
        public byte SearchSort { get; set; }
        public byte FastFullText { get; set; }
        public short ShelfLife { get; set; }
        public string Description { get; set; }
        public int LastAutorunHits { get; set; }
        public byte LimitToUserLibrary { get; set; }
        public Nullable<System.DateTime> LastAutorunDate { get; set; }
        public int ResultsFolder1 { get; set; }
        public int ResultsFolder2 { get; set; }
        public byte Autosearch { get; set; }
        public string UserDB { get; set; }
        public byte KeepDelete { get; set; }
    }
}
