//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestComment
    {
        public TestComment()
        {
            this.TestCommentCombos = new HashSet<TestCommentCombo>();
        }
    
        public int TestID { get; set; }
        public int id { get; set; }
        public int CommentID { get; set; }
        public string Comment { get; set; }
        public System.DateTime CommentDate { get; set; }
    
        public virtual ICollection<TestCommentCombo> TestCommentCombos { get; set; }
        public virtual Test Test { get; set; }
    }
}
