//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.TestComments = new HashSet<TestComment>();
            this.CitationsTests = new HashSet<CitationsTest>();
            this.TestsLinks = new HashSet<TestsLink>();
        }
    
        public int TestID { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
    
        public virtual ICollection<TestComment> TestComments { get; set; }
        public virtual ICollection<CitationsTest> CitationsTests { get; set; }
        public virtual ICollection<TestsLink> TestsLinks { get; set; }
    }
}
