//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCommentCombo
    {
        public int TestID { get; set; }
        public int id { get; set; }
        public int CommentID { get; set; }
        public int SpecialtyID { get; set; }
        public int TopicID { get; set; }
        public int SubTopicID { get; set; }
    
        public virtual TestComment TestComment { get; set; }
    }
}
