//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public int TopicID { get; set; }
        public int SpecialtyID { get; set; }
        public byte Type { get; set; }
        public Nullable<int> UserID { get; set; }
        public string TopicName { get; set; }
        public System.DateTime createtime { get; set; }
        public Nullable<int> LegacyID { get; set; }
    }
}
