//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHasSponsorFolder
    {
        public int UserId { get; set; }
        public int SponsorFolderId { get; set; }
        public Nullable<int> UserFolderId { get; set; }
        public Nullable<int> AutoQueryId { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
