//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AJA_UserEntities : DbContext
    {
        public AJA_UserEntities()
            : base("name=AJA_UserEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AJA_tbl_FieldOptions> AJA_tbl_FieldOptions { get; set; }
        public DbSet<AJA_tbl_FieldValues> AJA_tbl_FieldValues { get; set; }
        public DbSet<AJA_tbl_Roles> AJA_tbl_Roles { get; set; }
        public DbSet<AJA_tbl_UserFields> AJA_tbl_UserFields { get; set; }
        public DbSet<AJA_tbl_FieldTypes> AJA_tbl_FieldTypes { get; set; }
        public DbSet<Specialty> Specialties { get; set; }
        public DbSet<AJA_tbl_Users> AJA_tbl_Users { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<UserSpecialty> UserSpecialties { get; set; }
        public DbSet<SubTopic> SubTopics { get; set; }
        public DbSet<Topic> Topics { get; set; }
        public DbSet<TypePractice> TypePractices { get; set; }
    }
}
