//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCitation
    {
        public int UserID { get; set; }
        public int SubTopicID { get; set; }
        public int PMID { get; set; }
        public bool Deleted { get; set; }
        public bool IsAutoQueryCitation { get; set; }
        public int SearchID { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public bool KeepDelete { get; set; }
    }
}
