//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserComment
    {
        public int userid { get; set; }
        public int pmid { get; set; }
        public string nickname { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
